### ISSUE TITLE
http.sh test fails in centos6 passes in centos7

### ISSUE THREAD

**Issue by hugocruz** [varnish/vagent2#155]
When running the tests, 
In centos6 I get the output : 

```
FAIL: http.sh (exit: 4)
=======================

Temp directory: /tmp/vagent.5kl3mqdQ
Path to varnishd: /usr/sbin/varnishd
Starting backend: pid 26606.  port 47323.
Starting varnishd:  Started varnish. Pid 26625
Starting agent on port 14419:  Started agent. Pid 26866
Test 1: OK
Test 2: OK
Test 3: OK
Test 4: Failed:  GET html/index.html  200: GET http://agent:test@localhost:14419/html/index.html --> 200 OK
Test 5: OK
Test 6: Failed:  GET html/  200: GET http://agent:test@localhost:14419/html/ --> 200 OK
Test 7: OK
Test 8: Failed:  GET html  301: GET http://agent:test@localhost:14419/html --> 301 Moved Permanently
GET http://localhost:14419/html/ --> 401 Unauthorized
GET http://localhost:14419/html/ --> 200 OK
Test 9: OK
Test 10: OK
Test 11: Failed:  Location: header incorrect in redirect:
Stopping:  agent(26866) varnish(26625) backend(26606)
Cleaning up

````
Not sure if is the test_it_code() in the util.sh could be the reason for this issue.  response codes seem to be right for the tests. 
Same test,  passes in centos7 and debian. 
Any ideas?

**Comment by prajay** [comment]
I'm seeing the same error on Centos 6. This seems to be due to an older version of lwp-request being used on centos 6 compared to centos 5

Centos 6:
$ lwp-request -v
This is lwp-request version 5.827 (libwww-perl-5.833)

Copyright 1995-1999, Gisle Aas.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

Centos 5:
$ lwp-request -v
This is lwp-request version 6.09 (libwww-perl-6.13)

Copyright 1995-1999, Gisle Aas.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

It seems in the older version the Location header is not added

**Comment by hugocruz** [comment]
Hi, thank you for replying. I've reached the same conclusion. I'll look into some alternatives, in order to fix this.

**Comment by Dridi** [comment]
@hugocruz in #156 I suggest replacing `lwp-request` with `curl`. The latter never let me down :)

**Comment by hugocruz** [comment]
@Dridi yes, that seems to be the best option. Thanks.
