### ISSUE TITLE
memory leaks in vparams code

### ISSUE THREAD

**Issue by fgsch** [varnish/vagent2#168]
parse_value leaks tmp/orig if there is a default.

**Comment by fgsch** [comment]
vparams_show_json() also leaks pos when calling fill_entry in the while loop.

**Comment by Dridi** [comment]
Basically there's a lot of parsing going on, and this parsing code allocates copies of the input instead of only grabbing the pieces it needs. I'm constifying everything in order to never duplicate the input except when assigning `struct param_opt` members.

This is happening in #171 because I no longer have commit access to this repository.

**Comment by fgsch** [comment]
You have perms now.

**Comment by Dridi** [comment]
Thanks! If #171 is OK I will proceed with more similar changes.

**Comment by Dridi** [comment]
`vparams_show_json` also leaks the initial assignment for `tmp` [1] when it first calls `get_name_val` [2].

[1] https://github.com/varnish/vagent2/blob/a1d27be/src/modules/vparams.c#L298
[2] https://github.com/varnish/vagent2/blob/a1d27be/src/modules/vparams.c#L326

**Comment by Dridi** [comment]
I pushed my commits to the master branch, auto-merging the pull request. Feel free to either review the changes or close this issue.

**Comment by Dridi** [comment]
Timed out.
