### ISSUE TITLE
whitespace in probe string

### ISSUE THREAD

**Issue by marme660** [varnish/vagent2#173]
This is more like a question: 
@aondio I query /backendjson in agent and I am curious what the space in is "probe": "     Healthy (no probe)"

``` json
{
 "backends" : [
        {
            "name": "default(127.0.0.1,,80)",
            "ref": "1",
            "admin": "probe",
            "probe": "     Healthy (no probe)"
        }
]
}
```

_edit from @dridi: turned the json snippet into a block of code for better rendering._

**Comment by aondio** [comment]
Hi,
the extra whitespaces are due to the way the json output is generated.

From varnishstat we get a string that looks like this:
"default(127.0.0.1,,80)   1      probe       Healthy (no probe)"
to generate a json output we chunk the string into 4 parts and we take the last one as it is including spaces.

If you want further info on this, please pop in my office and I'll give the proper explanation. (pointers and strings are involved)
