### ISSUE TITLE
Assert error in _assert_VSB_integrity(), ../libvarnish/vsb.c line 91:

### ISSUE THREAD

**Issue by webbrandon** [varnish/vagent2#200]
**PROBLEM:**
When running `varnish-agent` the debug output reports failure seemingly upon missing file(or maybe failed curl response) which is the `favicon.ico`.  It crashes `varnish-agent`.

**ENVIRONMENT:**
Note this is being ran from a docker container.

- Debian Stretch 9
  - Varnish Cache 6.0.0 (from deb)
  - Varnish Agent 4.1.3 (from source)
  - Varnish Dashboard (https://github.com/brandonwamboldt/varnish-dashboard)

**COMMAND:**
```bash
varnish-agent \
    -T :6082 \
    -k allow-insecure-vac \
    -S /usr/local/etc/varnish/agent_secret \
    -z 0.0.0.0:8085 \
    -n varnish-1 \
    -H /var/www/html/varnish-dashboard \
    -d
```

**OUTPUT:**
```bash
main (main.c:355): Plugins initialized. -d argument given, so not forking.
LOGGER: send_curl (modules/vac_register.c:80): Sending VAC registration request: 0.0.0.0:6085
LOGGER: http_run (modules/http.c:456): HTTP starting on port 6085
LOGGER: issue_curl (modules/curl.c:109): Issuing curl command with url=0.0.0.0:6085. Request body present
LOGGER: log_request (modules/http.c:321): PUT /
LOGGER: log_request (modules/http.c:321): PUT /
LOGGER: log_request (modules/http.c:321): GET /
LOGGER: log_request (modules/http.c:321): GET /
LOGGER: log_request (modules/http.c:321): GET /favicon.ico
Assert error in _assert_VSB_integrity(), ../libvarnish/vsb.c line 91:
  Condition(s->s_len < s->s_size) not true.
  errno = 2 (No such file or directory)
./entrypoint.sh: line 16:    17 Aborted                 varnish-agent -T :6082 -k allow-insecure-vac -S /usr/local/etc/varnish/agent_secret -z 0.0.0.0:${AGENT_PORT} -n varnish-${AGENT_PORT} -H /var/www/html/varnish-dashboard -d
```

**Comment by Dridi** [comment]
We don't support Varnish 6 and aren't planning to do so in the foreseeable future, sorry. :(

**Comment by webbrandon** [comment]
Would you have any idea of the cause of this.  I don't mind digging deeper and committing fixes if I find them.

**Comment by Dridi** [comment]
The parsing code could be very much improved by failing gracefully instead of asserting and thus crashing whenever `varnishd` changes its output. As it stands it can read the output of the supported/used CLI commands from Varnish 3.0 to 4.1, so any change is bound to crash from 5.0 onward.

A couple of us already greatly improved the robustness of the parsing code for a couple CLI commands but in its current state it's not sustainable. There are plans to change the output of the Varnish CLI to JSON that would supposedly ease parsing (at least we could delegate the JSON unmarshaling to an off-the-shelf library) but we are not there yet.

There is at least one person in the Varnish team increasing JSON coverage in the CLI and once we're there we can hope to revive support for newer versions (and with such a radical change probably drop support for older non-JSON-capable versions). Currently vagent2 is maintained to support Varnish up to 4.1, a branch still supported upstream.

If SomeOne:tm: were to do us a huge solid and add full support for more recent versions (like 6.0 for example) we'd definitely review the patches. The test suite is also a bit of a pain to maintain...

Even if you decide not to proceed, thanks for asking and at least showing interest in moving things forward!

**Comment by Dridi** [comment]
You shouldn't need the '-k' and '-z' options.
